In [3]:
import torch
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

1.8.1+cu102
True


In [4]:
# 生成固定shape的均匀分布的随机数
x = torch.rand(size=(2, 3))
x

tensor([[0.1836, 0.8353, 0.8176],
        [0.6405, 0.4905, 0.7342]])

In [5]:
x = torch.randn(size=(2, 3))
x

tensor([[ 1.6366, -0.2849, -0.4096],
        [-1.5742, -1.3502,  0.7467]])

In [6]:
x = torch.zeros(size=(2, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
x = torch.ones(size=(2, 3, 4), dtype=torch.float32)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
# shape和size的区别：https://blog.csdn.net/CQUSongYuxin/article/details/107379150
x.size() # 使用size这个方法返回x这个tensor的形状

torch.Size([2, 3, 4])

In [8]:
x.shape # 也可以使用shape这个属性返回x的形状

torch.Size([2, 3, 4])

In [14]:
# x.size()与shape的实现效果相同，好处在于size()方法能够对形状数组(torch.Size([2, 3, 4]))中的值进行切片
x.size(-1)

4

In [11]:
x.shape[-1] # shape属性也能进行，不过shape采用的是切片的方式获取

4

In [ ]:
# 数据类型：
"""
64位浮点型：torch.float64
32位浮点型：torch.float32
32位整型：torch.int32
16位整型：torch.int16
64位整型：torch.int64
"""

In [4]:
"""
通过torch.tensor将列表直接转换为tensor, 类似numpy.array(data, dtype);
"""
x = torch.tensor(data=[6, 2], dtype=torch.float32)
x.type()

'torch.FloatTensor'

In [23]:
# 将float32类型的数据转化为其他数据类型
x = x.type(dtype=torch.int64)
x.type()

'torch.LongTensor'

In [30]:
# tensor与numpy数据类型的转换
x = np.random.randn(2, 3)
x

array([[-0.40686424,  0.88599022, -1.14748379],
       [ 0.27355626,  0.43817394, -0.66570884]])

In [31]:
x = torch.from_numpy(x)
x

tensor([[-0.4069,  0.8860, -1.1475],
        [ 0.2736,  0.4382, -0.6657]], dtype=torch.float64)

In [55]:
x.numpy()

array([[-0.55233842, -0.80747907, -1.13826822],
       [ 0.3642144 ,  0.90537777,  0.51207917]])

## 张量的计算

In [5]:
x1 = torch.rand(size=(2, 3))
x2 = torch.rand(size=(2, 3))
# x3 = x1 + x2 这种直接的方式就是将两者相加的结果赋予一个新的变量x3，而x1和x2的值并未改变
# x1.add(x2) 这种方式也是一样，x1和x2的值并未改变，相加结果返回
x1.add_(x2) #这种方式会将相加的结果赋予x1，使得x1的值改变,这种加上下划线的函数代表就地改变这个变量

tensor([[1.7051, 1.7564, 1.1035],
        [0.5315, 0.4932, 1.0755]])

In [6]:
x1.reshape(shape=(3, 2))

tensor([[1.7051, 1.7564],
        [1.1035, 0.5315],
        [0.4932, 1.0755]])

In [7]:
# pytorch view可以将tensor的形状进行修改
x1.view(size=(3, 2))

tensor([[1.7051, 1.7564],
        [1.1035, 0.5315],
        [0.4932, 1.0755]])

In [8]:
x1.reshape(shape=(-1, 1))

tensor([[1.7051],
        [1.7564],
        [1.1035],
        [0.5315],
        [0.4932],
        [1.0755]])

In [9]:
x1.view(size=(-1, 1))

tensor([[1.7051],
        [1.7564],
        [1.1035],
        [0.5315],
        [0.4932],
        [1.0755]])

In [ ]:
# view与reshape的区别
# 1. https://blog.csdn.net/zplai/article/details/111416053
# 2. https://blog.csdn.net/weixin_43002433/article/details/104299896?utm_medium=distribute.pc_relevant.none-task-blog-baidujs_title-0&spm=1001.2101.3001.4242
# 3. https://blog.csdn.net/Flag_ing/article/details/109129752?utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link#commentBox
"""
前提：python的变量和数据是保存在不同的内存空间中的，PyTorch中的Tensor的存储也是类似的机制，tensor相当于python变量，
保存了tensor的形状(size)、步长(stride)、数据类型(type)等信息(或其引用)，当然也保存了对其对应的存储器Storage的引用，
存储器Storage就是对数据data的封装。
viewed对象和reshaped对象都存储在与原始对象不同的地址内存中，但是它们共享存储器Storage，也就意味着它们共享基础数据。
"""

In [10]:
x1.mean()

tensor(1.1109)

In [12]:
x1 = x1.sum()
type(x1)

torch.Tensor

In [98]:
x1.item() # 通过item()的方式可以将只有一个值的tensor的那个标量值取出

6.238728046417236

## 张量的自动微分
>将torch.Tensor属性中，如果将requires_grad设置为True，pytorch将开始跟踪对此张量的所有操作，完成计算后，可以调用.backward()并自动计算所有的梯度，该张量的梯度将累加到.grad属性中

In [14]:
# torch中一个Tensor张量数据包含三部分属性：
# 1. data属性，也即记录这个张量的数据具体是多少；
# 2. grad属性，代表张量的梯度，如果requires_grad=true的时候，则.backward()计算得到的梯度值就会被累加在这个张量的.grad这个属性中，
#    这说明requires_grad=true时，变量的所有运行操作会被跟踪记录，用于后续计算梯度；
# 3. grad_fn属性，用于记录被计算出来的grad的值是由什么func计算得来的
x = torch.ones(size=(2, 2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [ ]:
x.requires_grad

In [15]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [16]:
x.grad

In [17]:
x.grad_fn

In [19]:
y = x + 2 # 广播机制
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [20]:
y.grad_fn

In [21]:
z = y*y + 3

In [22]:
out = z.mean()
out

tensor(12., grad_fn=<MeanBackward0>)

In [23]:
out.backward() # d out / dx，这一步是求微分的操作
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [24]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [25]:
with torch.no_grad():
    print((x**2).requires_grad)
# with torch.no_grad() <=====> x.detach()

False


In [27]:
# e.g.:
y = x.detach()
y.requires_grad

False

In [138]:
# 当一个tensor变量的requires_grad为False时，此时想要将其转换为requires_grad=True
# 可以利用xxxtensor.requires_grad_(True)的方式改变这个tensor的requires_grad属性
# 其中requires_grad_带有下划线，可以直接在该tensor身上进行改变，从而改变该tensor的属性
a = torch.tensor([2, 3], dtype=torch.float32)
a.requires_grad_(True) #只有float类型的tensor才能使用requires_grad_

tensor([2., 3.], requires_grad=True)