In [36]:
import torch
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

1.8.1+cu101
True


In [3]:
# 生成固定shape的均匀分布的随机数
x = torch.rand(size=(2, 3))
x

tensor([[0.1653, 0.3245, 0.5600],
        [0.7287, 0.5149, 0.8560]])

In [4]:
x = torch.randn(size=(2, 3))
x

tensor([[ 0.2460,  0.9664,  1.7152],
        [-0.6973, -0.3124,  0.5289]])

In [6]:
x = torch.zeros(size=(2, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [46]:
x = torch.ones(size=(2, 3, 4), dtype=torch.float32)
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
x.size()

torch.Size([2, 3, 4])

In [12]:
x.shape

torch.Size([2, 3, 4])

In [14]:
# x.size()与shape的实现效果相同，好处在于size()方法能够对尺寸数组中的值进行切片
x.size(-1)

4

In [ ]:
# 数据类型：
"""
32位浮点型：torch.float32
"""

In [37]:
x = torch.tensor(data=[6, 2], dtype=torch.float32)
x

tensor([6., 2.])

In [44]:
# 将float32类型的数据转化为其他数据类型
x.type(dtype=torch.int64)
x

tensor([6., 2.])

In [53]:
# tensor与numpy数据类型的转换
x = np.random.randn(2, 3)
x

array([[-0.55233842, -0.80747907, -1.13826822],
       [ 0.3642144 ,  0.90537777,  0.51207917]])

In [54]:
x = torch.from_numpy(x)
x

tensor([[-0.5523, -0.8075, -1.1383],
        [ 0.3642,  0.9054,  0.5121]], dtype=torch.float64)

In [55]:
x.numpy()

array([[-0.55233842, -0.80747907, -1.13826822],
       [ 0.3642144 ,  0.90537777,  0.51207917]])

## 张量的计算

In [90]:
x1 = torch.rand(size=(2, 3))
x2 = torch.rand(size=(2, 3))
# x3 = x1 + x2 这种直接的方式就是将两者相加的结果赋予一个新的变量x3，而x1和x2的值并未改变
# x1.add(x2) 这种方式也是一样，x1和x2的值并未改变，相加结果返回
x1.add_(x2) #这种方式会将相加的结果赋予x1，使得x1的值改变,这种加上下划线的函数代表就地改变这个变量

tensor([[0.9407, 1.1364, 1.2806],
        [0.4761, 1.5148, 0.8901]])

In [79]:
x1.reshape(shape=(3, 2))

In [81]:
x1.view(size=(3, 2))

tensor([[0.9255, 1.3272],
        [1.1276, 1.1031],
        [0.7325, 0.4548]])

In [82]:
x1.reshape(shape=(-1, 1))

In [83]:
x1.view(size=(-1, 1))

tensor([[0.9255],
        [1.3272],
        [1.1276],
        [1.1031],
        [0.7325],
        [0.4548]])

In [ ]:
# view与reshape的区别
# 1. https://blog.csdn.net/zplai/article/details/111416053
# 2. https://blog.csdn.net/weixin_43002433/article/details/104299896?utm_medium=distribute.pc_relevant.none-task-blog-baidujs_title-0&spm=1001.2101.3001.4242

In [87]:
# x1.mean()

tensor(0.9451)

In [97]:
x1 = x1.sum()
x1

tensor(6.2387)

In [98]:
x1.item()

6.238728046417236

## 张量的自动微分
>将torch.Tensor属性中，如果将requires_grad设置为True，pytorch将开始跟踪对此张量的所有操作，完成计算后，可以调用.backward()并自动计算所有的梯度，该张量的梯度将累加到.grad属性中

In [125]:
# torch中一个Tensor张量数据包含三部分属性：
# 1. data属性，也即记录这个张量的数据具体是多少；
# 2. grad属性，代表张量的梯度，如果requires_grad=true的时候，则.backward()计算得到的梯度值就会被记录在这个张量的grad这个属性中；
# 3. grad_fn属性，用于记录被计算出来的grad的值是由什么func计算得来的
x = torch.ones(size=(2, 2), requires_grad=True)
x.requires_grad

True

In [126]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [127]:
x.grad

In [128]:
x.grad_fn

In [129]:
y = x + 2 # 广播机制
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [130]:
y.grad_fn

In [131]:
z = y*y + 3

In [132]:
out = z.mean()
out

tensor(12., grad_fn=<MeanBackward0>)

In [133]:
out.backward() # d out / dx，这一步是求微分的操作
x.grad

tensor([[1.5000, 1.5000],
        [1.5000, 1.5000]])

In [134]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [136]:
with torch.no_grad():
    print((x**2).requires_grad)
# with torch.no_grad() <=====> x.detach()

False


In [138]:
a = torch.tensor([2, 3], dtype=torch.float32)
a.requires_grad_(True) #只有float类型的tensor才能使用requires_grad_

tensor([2., 3.], requires_grad=True)